package saasdb

import "github.com/flipped-aurora/gin-vue-admin/server/api/v1/saasdb/taskclient"

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	InstanceApi
	HostApi
	DomainApi
	ProjectApi
	BackLogApi
	taskclient.ClientApiGroup
	ClusterApi
	OggInfoApi
	DBOverViewApi
	SaasOracleProjectUserApi
	SaasOracleDbApi
	SaasOracleInstanceApi
	SaasOracleIpMappingApi
	SaasOracleIpApi
	SaasDictumApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
