-- 创建默认的数据库账号和完成授权 --
-- author: milky star --
-- email: haochen@corp.netease.com --

set sql_log_bin=0;

-- proj_sa --
DROP USER IF EXISTS 'proj_sa'@'%';
CREATE USER 'proj_sa'@'%' IDENTIFIED WITH mysql_native_password BY 'A424970F97C19A2E88CF72038C039' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK;
GRANT SELECT, RELOAD, PROCESS, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'proj_sa'@'%';


-- repl --
DROP USER IF EXISTS 'repl'@'%';
CREATE USER 'repl'@'%' IDENTIFIED WITH mysql_native_password BY '3665156F23D8C05603DC53EBAD2D7E374' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK;
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'repl'@'%';

-- monitor --
CREATE USER 'pmm'@'localhost' IDENTIFIED BY 'pass' WITH MAX_USER_CONNECTIONS 10;
GRANT SELECT, PROCESS, REPLICATION CLIENT, RELOAD, BACKUP_ADMIN ON *.* TO 'pmm'@'localhost';

-- saasdb_admin --
DROP USER IF EXISTS 'saasdb_admin'@'127.0.0.1';
CREATE USER 'saasdb_admin'@'127.0.0.1' IDENTIFIED WITH 'mysql_native_password' AS '*84F85C2180F3305F7058C5463AAD498EFE72DAAE' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK;
GRANT SELECT, RELOAD, PROCESS, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'saasdb_admin'@'127.0.0.1';

-- backup --
DROP USER IF EXISTS 'backup'@'%';
CREATE USER 'backup'@'%' IDENTIFIED WITH 'mysql_native_password' AS '*84F85C2180F3305F7058C5463AAD498EFE72DAAE' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK;
GRANT BACKUP_ADMIN on *.* TO 'backup'@'%';

