// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: web_hook.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OpDeadMasterServiceClient is the client API for OpDeadMasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpDeadMasterServiceClient interface {
	HandleDeadMaster(ctx context.Context, in *DeadMasterRequest, opts ...grpc.CallOption) (*DeadMasterResponse, error)
}

type opDeadMasterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOpDeadMasterServiceClient(cc grpc.ClientConnInterface) OpDeadMasterServiceClient {
	return &opDeadMasterServiceClient{cc}
}

func (c *opDeadMasterServiceClient) HandleDeadMaster(ctx context.Context, in *DeadMasterRequest, opts ...grpc.CallOption) (*DeadMasterResponse, error) {
	out := new(DeadMasterResponse)
	err := c.cc.Invoke(ctx, "/OpDeadMasterService/HandleDeadMaster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpDeadMasterServiceServer is the server API for OpDeadMasterService service.
// All implementations must embed UnimplementedOpDeadMasterServiceServer
// for forward compatibility
type OpDeadMasterServiceServer interface {
	HandleDeadMaster(context.Context, *DeadMasterRequest) (*DeadMasterResponse, error)
	mustEmbedUnimplementedOpDeadMasterServiceServer()
}

// UnimplementedOpDeadMasterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOpDeadMasterServiceServer struct {
}

func (UnimplementedOpDeadMasterServiceServer) HandleDeadMaster(context.Context, *DeadMasterRequest) (*DeadMasterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleDeadMaster not implemented")
}
func (UnimplementedOpDeadMasterServiceServer) mustEmbedUnimplementedOpDeadMasterServiceServer() {}

// UnsafeOpDeadMasterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpDeadMasterServiceServer will
// result in compilation errors.
type UnsafeOpDeadMasterServiceServer interface {
	mustEmbedUnimplementedOpDeadMasterServiceServer()
}

func RegisterOpDeadMasterServiceServer(s grpc.ServiceRegistrar, srv OpDeadMasterServiceServer) {
	s.RegisterService(&OpDeadMasterService_ServiceDesc, srv)
}

func _OpDeadMasterService_HandleDeadMaster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeadMasterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpDeadMasterServiceServer).HandleDeadMaster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OpDeadMasterService/HandleDeadMaster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpDeadMasterServiceServer).HandleDeadMaster(ctx, req.(*DeadMasterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OpDeadMasterService_ServiceDesc is the grpc.ServiceDesc for OpDeadMasterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpDeadMasterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "OpDeadMasterService",
	HandlerType: (*OpDeadMasterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleDeadMaster",
			Handler:    _OpDeadMasterService_HandleDeadMaster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "web_hook.proto",
}

// OpNewMasterServiceClient is the client API for OpNewMasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpNewMasterServiceClient interface {
	HandleNewMaster(ctx context.Context, in *NewMasterRequest, opts ...grpc.CallOption) (*NewMasterResponse, error)
}

type opNewMasterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOpNewMasterServiceClient(cc grpc.ClientConnInterface) OpNewMasterServiceClient {
	return &opNewMasterServiceClient{cc}
}

func (c *opNewMasterServiceClient) HandleNewMaster(ctx context.Context, in *NewMasterRequest, opts ...grpc.CallOption) (*NewMasterResponse, error) {
	out := new(NewMasterResponse)
	err := c.cc.Invoke(ctx, "/OpNewMasterService/HandleNewMaster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpNewMasterServiceServer is the server API for OpNewMasterService service.
// All implementations must embed UnimplementedOpNewMasterServiceServer
// for forward compatibility
type OpNewMasterServiceServer interface {
	HandleNewMaster(context.Context, *NewMasterRequest) (*NewMasterResponse, error)
	mustEmbedUnimplementedOpNewMasterServiceServer()
}

// UnimplementedOpNewMasterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOpNewMasterServiceServer struct {
}

func (UnimplementedOpNewMasterServiceServer) HandleNewMaster(context.Context, *NewMasterRequest) (*NewMasterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleNewMaster not implemented")
}
func (UnimplementedOpNewMasterServiceServer) mustEmbedUnimplementedOpNewMasterServiceServer() {}

// UnsafeOpNewMasterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpNewMasterServiceServer will
// result in compilation errors.
type UnsafeOpNewMasterServiceServer interface {
	mustEmbedUnimplementedOpNewMasterServiceServer()
}

func RegisterOpNewMasterServiceServer(s grpc.ServiceRegistrar, srv OpNewMasterServiceServer) {
	s.RegisterService(&OpNewMasterService_ServiceDesc, srv)
}

func _OpNewMasterService_HandleNewMaster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewMasterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpNewMasterServiceServer).HandleNewMaster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OpNewMasterService/HandleNewMaster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpNewMasterServiceServer).HandleNewMaster(ctx, req.(*NewMasterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OpNewMasterService_ServiceDesc is the grpc.ServiceDesc for OpNewMasterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpNewMasterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "OpNewMasterService",
	HandlerType: (*OpNewMasterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleNewMaster",
			Handler:    _OpNewMasterService_HandleNewMaster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "web_hook.proto",
}
