// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: db_func_slow_log_query.proto

package grpc_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MySQLSlowLogQueryServiceClient is the client API for MySQLSlowLogQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MySQLSlowLogQueryServiceClient interface {
	NewGetSlowQuery(ctx context.Context, in *SlowLogQueryRequest, opts ...grpc.CallOption) (*SlowLogQueryResponse, error)
}

type mySQLSlowLogQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMySQLSlowLogQueryServiceClient(cc grpc.ClientConnInterface) MySQLSlowLogQueryServiceClient {
	return &mySQLSlowLogQueryServiceClient{cc}
}

func (c *mySQLSlowLogQueryServiceClient) NewGetSlowQuery(ctx context.Context, in *SlowLogQueryRequest, opts ...grpc.CallOption) (*SlowLogQueryResponse, error) {
	out := new(SlowLogQueryResponse)
	err := c.cc.Invoke(ctx, "/saasdb.MySQLSlowLogQueryService/NewGetSlowQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MySQLSlowLogQueryServiceServer is the server API for MySQLSlowLogQueryService service.
// All implementations must embed UnimplementedMySQLSlowLogQueryServiceServer
// for forward compatibility
type MySQLSlowLogQueryServiceServer interface {
	NewGetSlowQuery(context.Context, *SlowLogQueryRequest) (*SlowLogQueryResponse, error)
	mustEmbedUnimplementedMySQLSlowLogQueryServiceServer()
}

// UnimplementedMySQLSlowLogQueryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMySQLSlowLogQueryServiceServer struct {
}

func (UnimplementedMySQLSlowLogQueryServiceServer) NewGetSlowQuery(context.Context, *SlowLogQueryRequest) (*SlowLogQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewGetSlowQuery not implemented")
}
func (UnimplementedMySQLSlowLogQueryServiceServer) mustEmbedUnimplementedMySQLSlowLogQueryServiceServer() {
}

// UnsafeMySQLSlowLogQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MySQLSlowLogQueryServiceServer will
// result in compilation errors.
type UnsafeMySQLSlowLogQueryServiceServer interface {
	mustEmbedUnimplementedMySQLSlowLogQueryServiceServer()
}

func RegisterMySQLSlowLogQueryServiceServer(s grpc.ServiceRegistrar, srv MySQLSlowLogQueryServiceServer) {
	s.RegisterService(&MySQLSlowLogQueryService_ServiceDesc, srv)
}

func _MySQLSlowLogQueryService_NewGetSlowQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlowLogQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySQLSlowLogQueryServiceServer).NewGetSlowQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saasdb.MySQLSlowLogQueryService/NewGetSlowQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySQLSlowLogQueryServiceServer).NewGetSlowQuery(ctx, req.(*SlowLogQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MySQLSlowLogQueryService_ServiceDesc is the grpc.ServiceDesc for MySQLSlowLogQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MySQLSlowLogQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saasdb.MySQLSlowLogQueryService",
	HandlerType: (*MySQLSlowLogQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewGetSlowQuery",
			Handler:    _MySQLSlowLogQueryService_NewGetSlowQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db_func_slow_log_query.proto",
}
