// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: db_func_handle_variables.proto

package grpc_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MySQLVariablesServiceClient is the client API for MySQLVariablesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MySQLVariablesServiceClient interface {
	VariablesHandler(ctx context.Context, in *HandleVariablesRequest, opts ...grpc.CallOption) (*HandleVariablesResponse, error)
}

type mySQLVariablesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMySQLVariablesServiceClient(cc grpc.ClientConnInterface) MySQLVariablesServiceClient {
	return &mySQLVariablesServiceClient{cc}
}

func (c *mySQLVariablesServiceClient) VariablesHandler(ctx context.Context, in *HandleVariablesRequest, opts ...grpc.CallOption) (*HandleVariablesResponse, error) {
	out := new(HandleVariablesResponse)
	err := c.cc.Invoke(ctx, "/saasdb.MySQLVariablesService/VariablesHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MySQLVariablesServiceServer is the server API for MySQLVariablesService service.
// All implementations must embed UnimplementedMySQLVariablesServiceServer
// for forward compatibility
type MySQLVariablesServiceServer interface {
	VariablesHandler(context.Context, *HandleVariablesRequest) (*HandleVariablesResponse, error)
	mustEmbedUnimplementedMySQLVariablesServiceServer()
}

// UnimplementedMySQLVariablesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMySQLVariablesServiceServer struct {
}

func (UnimplementedMySQLVariablesServiceServer) VariablesHandler(context.Context, *HandleVariablesRequest) (*HandleVariablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VariablesHandler not implemented")
}
func (UnimplementedMySQLVariablesServiceServer) mustEmbedUnimplementedMySQLVariablesServiceServer() {}

// UnsafeMySQLVariablesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MySQLVariablesServiceServer will
// result in compilation errors.
type UnsafeMySQLVariablesServiceServer interface {
	mustEmbedUnimplementedMySQLVariablesServiceServer()
}

func RegisterMySQLVariablesServiceServer(s grpc.ServiceRegistrar, srv MySQLVariablesServiceServer) {
	s.RegisterService(&MySQLVariablesService_ServiceDesc, srv)
}

func _MySQLVariablesService_VariablesHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySQLVariablesServiceServer).VariablesHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saasdb.MySQLVariablesService/VariablesHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySQLVariablesServiceServer).VariablesHandler(ctx, req.(*HandleVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MySQLVariablesService_ServiceDesc is the grpc.ServiceDesc for MySQLVariablesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MySQLVariablesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saasdb.MySQLVariablesService",
	HandlerType: (*MySQLVariablesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VariablesHandler",
			Handler:    _MySQLVariablesService_VariablesHandler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db_func_handle_variables.proto",
}
