// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: ins_metric_instance_base.proto

package grpc_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//定义消息
type InsMetricRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MySQLIP   string `protobuf:"bytes,1,opt,name=MySQLIP,proto3" json:"MySQLIP,omitempty"`
	MySQLPort int32  `protobuf:"varint,2,opt,name=MySQLPort,proto3" json:"MySQLPort,omitempty"`
}

func (x *InsMetricRequest) Reset() {
	*x = InsMetricRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ins_metric_instance_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsMetricRequest) ProtoMessage() {}

func (x *InsMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ins_metric_instance_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsMetricRequest.ProtoReflect.Descriptor instead.
func (*InsMetricRequest) Descriptor() ([]byte, []int) {
	return file_ins_metric_instance_base_proto_rawDescGZIP(), []int{0}
}

func (x *InsMetricRequest) GetMySQLIP() string {
	if x != nil {
		return x.MySQLIP
	}
	return ""
}

func (x *InsMetricRequest) GetMySQLPort() int32 {
	if x != nil {
		return x.MySQLPort
	}
	return 0
}

type InsMetricResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InsMetric *InsMetric `protobuf:"bytes,1,opt,name=InsMetric,proto3" json:"InsMetric,omitempty"`
}

func (x *InsMetricResponse) Reset() {
	*x = InsMetricResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ins_metric_instance_base_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsMetricResponse) ProtoMessage() {}

func (x *InsMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ins_metric_instance_base_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsMetricResponse.ProtoReflect.Descriptor instead.
func (*InsMetricResponse) Descriptor() ([]byte, []int) {
	return file_ins_metric_instance_base_proto_rawDescGZIP(), []int{1}
}

func (x *InsMetricResponse) GetInsMetric() *InsMetric {
	if x != nil {
		return x.InsMetric
	}
	return nil
}

type InsMetric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IP         string `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Port       int32  `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	DeployPath string `protobuf:"bytes,3,opt,name=DeployPath,proto3" json:"DeployPath,omitempty"`
	Version    string `protobuf:"bytes,4,opt,name=Version,proto3" json:"Version,omitempty"`
	StartTime  string `protobuf:"bytes,5,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	Status     bool   `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *InsMetric) Reset() {
	*x = InsMetric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ins_metric_instance_base_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsMetric) ProtoMessage() {}

func (x *InsMetric) ProtoReflect() protoreflect.Message {
	mi := &file_ins_metric_instance_base_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsMetric.ProtoReflect.Descriptor instead.
func (*InsMetric) Descriptor() ([]byte, []int) {
	return file_ins_metric_instance_base_proto_rawDescGZIP(), []int{2}
}

func (x *InsMetric) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *InsMetric) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *InsMetric) GetDeployPath() string {
	if x != nil {
		return x.DeployPath
	}
	return ""
}

func (x *InsMetric) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InsMetric) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *InsMetric) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_ins_metric_instance_base_proto protoreflect.FileDescriptor

var file_ins_metric_instance_base_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x69, 0x6e, 0x73, 0x5f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x5f, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x73, 0x61, 0x61, 0x73, 0x64, 0x62, 0x22, 0x4a, 0x0a, 0x10, 0x49, 0x6e, 0x73, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x79, 0x53, 0x51, 0x4c, 0x49, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d,
	0x79, 0x53, 0x51, 0x4c, 0x49, 0x50, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x50,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x4d, 0x79, 0x53, 0x51, 0x4c,
	0x50, 0x6f, 0x72, 0x74, 0x22, 0x44, 0x0a, 0x11, 0x49, 0x6e, 0x73, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x09, 0x49, 0x6e, 0x73,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73,
	0x61, 0x61, 0x73, 0x64, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52,
	0x09, 0x49, 0x6e, 0x73, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x22, 0x9f, 0x01, 0x0a, 0x09, 0x49,
	0x6e, 0x73, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x50, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x59, 0x0a, 0x10,
	0x49, 0x6e, 0x73, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x45, 0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x49, 0x6e, 0x73, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x12, 0x18, 0x2e, 0x73, 0x61, 0x61, 0x73, 0x64, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x61, 0x61,
	0x73, 0x64, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x70, 0x62, 0x2f, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ins_metric_instance_base_proto_rawDescOnce sync.Once
	file_ins_metric_instance_base_proto_rawDescData = file_ins_metric_instance_base_proto_rawDesc
)

func file_ins_metric_instance_base_proto_rawDescGZIP() []byte {
	file_ins_metric_instance_base_proto_rawDescOnce.Do(func() {
		file_ins_metric_instance_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_ins_metric_instance_base_proto_rawDescData)
	})
	return file_ins_metric_instance_base_proto_rawDescData
}

var file_ins_metric_instance_base_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ins_metric_instance_base_proto_goTypes = []interface{}{
	(*InsMetricRequest)(nil),  // 0: saasdb.InsMetricRequest
	(*InsMetricResponse)(nil), // 1: saasdb.InsMetricResponse
	(*InsMetric)(nil),         // 2: saasdb.InsMetric
}
var file_ins_metric_instance_base_proto_depIdxs = []int32{
	2, // 0: saasdb.InsMetricResponse.InsMetric:type_name -> saasdb.InsMetric
	0, // 1: saasdb.InsMetricService.NewInsMetric:input_type -> saasdb.InsMetricRequest
	1, // 2: saasdb.InsMetricService.NewInsMetric:output_type -> saasdb.InsMetricResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ins_metric_instance_base_proto_init() }
func file_ins_metric_instance_base_proto_init() {
	if File_ins_metric_instance_base_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ins_metric_instance_base_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsMetricRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ins_metric_instance_base_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsMetricResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ins_metric_instance_base_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsMetric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ins_metric_instance_base_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ins_metric_instance_base_proto_goTypes,
		DependencyIndexes: file_ins_metric_instance_base_proto_depIdxs,
		MessageInfos:      file_ins_metric_instance_base_proto_msgTypes,
	}.Build()
	File_ins_metric_instance_base_proto = out.File
	file_ins_metric_instance_base_proto_rawDesc = nil
	file_ins_metric_instance_base_proto_goTypes = nil
	file_ins_metric_instance_base_proto_depIdxs = nil
}
