// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: ins_metric_instance_base.proto

package grpc_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InsMetricServiceClient is the client API for InsMetricService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InsMetricServiceClient interface {
	NewInsMetric(ctx context.Context, in *InsMetricRequest, opts ...grpc.CallOption) (*InsMetricResponse, error)
}

type insMetricServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInsMetricServiceClient(cc grpc.ClientConnInterface) InsMetricServiceClient {
	return &insMetricServiceClient{cc}
}

func (c *insMetricServiceClient) NewInsMetric(ctx context.Context, in *InsMetricRequest, opts ...grpc.CallOption) (*InsMetricResponse, error) {
	out := new(InsMetricResponse)
	err := c.cc.Invoke(ctx, "/saasdb.InsMetricService/NewInsMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InsMetricServiceServer is the server API for InsMetricService service.
// All implementations must embed UnimplementedInsMetricServiceServer
// for forward compatibility
type InsMetricServiceServer interface {
	NewInsMetric(context.Context, *InsMetricRequest) (*InsMetricResponse, error)
	mustEmbedUnimplementedInsMetricServiceServer()
}

// UnimplementedInsMetricServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInsMetricServiceServer struct {
}

func (UnimplementedInsMetricServiceServer) NewInsMetric(context.Context, *InsMetricRequest) (*InsMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewInsMetric not implemented")
}
func (UnimplementedInsMetricServiceServer) mustEmbedUnimplementedInsMetricServiceServer() {}

// UnsafeInsMetricServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InsMetricServiceServer will
// result in compilation errors.
type UnsafeInsMetricServiceServer interface {
	mustEmbedUnimplementedInsMetricServiceServer()
}

func RegisterInsMetricServiceServer(s grpc.ServiceRegistrar, srv InsMetricServiceServer) {
	s.RegisterService(&InsMetricService_ServiceDesc, srv)
}

func _InsMetricService_NewInsMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsMetricServiceServer).NewInsMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saasdb.InsMetricService/NewInsMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsMetricServiceServer).NewInsMetric(ctx, req.(*InsMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InsMetricService_ServiceDesc is the grpc.ServiceDesc for InsMetricService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InsMetricService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saasdb.InsMetricService",
	HandlerType: (*InsMetricServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewInsMetric",
			Handler:    _InsMetricService_NewInsMetric_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ins_metric_instance_base.proto",
}
