// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: orchestrator_webhook.proto

package grpc_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operator Dead Master
type OrchWebHookDeadMasterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeadMasterAddress string `protobuf:"bytes,1,opt,name=DeadMasterAddress,proto3" json:"DeadMasterAddress,omitempty"`
}

func (x *OrchWebHookDeadMasterRequest) Reset() {
	*x = OrchWebHookDeadMasterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchestrator_webhook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchWebHookDeadMasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchWebHookDeadMasterRequest) ProtoMessage() {}

func (x *OrchWebHookDeadMasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_webhook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchWebHookDeadMasterRequest.ProtoReflect.Descriptor instead.
func (*OrchWebHookDeadMasterRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *OrchWebHookDeadMasterRequest) GetDeadMasterAddress() string {
	if x != nil {
		return x.DeadMasterAddress
	}
	return ""
}

type OrchWebHookDeadMasterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageInfo  string `protobuf:"bytes,1,opt,name=MessageInfo,proto3" json:"MessageInfo,omitempty"`
	MessageWarn  string `protobuf:"bytes,2,opt,name=MessageWarn,proto3" json:"MessageWarn,omitempty"`
	MessageError string `protobuf:"bytes,3,opt,name=MessageError,proto3" json:"MessageError,omitempty"`
}

func (x *OrchWebHookDeadMasterResponse) Reset() {
	*x = OrchWebHookDeadMasterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchestrator_webhook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchWebHookDeadMasterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchWebHookDeadMasterResponse) ProtoMessage() {}

func (x *OrchWebHookDeadMasterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_webhook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchWebHookDeadMasterResponse.ProtoReflect.Descriptor instead.
func (*OrchWebHookDeadMasterResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_webhook_proto_rawDescGZIP(), []int{1}
}

func (x *OrchWebHookDeadMasterResponse) GetMessageInfo() string {
	if x != nil {
		return x.MessageInfo
	}
	return ""
}

func (x *OrchWebHookDeadMasterResponse) GetMessageWarn() string {
	if x != nil {
		return x.MessageWarn
	}
	return ""
}

func (x *OrchWebHookDeadMasterResponse) GetMessageError() string {
	if x != nil {
		return x.MessageError
	}
	return ""
}

// Operator New Master
type OrchWebHookNewMasterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewMasterAddress string `protobuf:"bytes,1,opt,name=NewMasterAddress,proto3" json:"NewMasterAddress,omitempty"`
}

func (x *OrchWebHookNewMasterRequest) Reset() {
	*x = OrchWebHookNewMasterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchestrator_webhook_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchWebHookNewMasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchWebHookNewMasterRequest) ProtoMessage() {}

func (x *OrchWebHookNewMasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_webhook_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchWebHookNewMasterRequest.ProtoReflect.Descriptor instead.
func (*OrchWebHookNewMasterRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_webhook_proto_rawDescGZIP(), []int{2}
}

func (x *OrchWebHookNewMasterRequest) GetNewMasterAddress() string {
	if x != nil {
		return x.NewMasterAddress
	}
	return ""
}

type OrchWebHookNewMasterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageInfo  string `protobuf:"bytes,1,opt,name=MessageInfo,proto3" json:"MessageInfo,omitempty"`
	MessageWarn  string `protobuf:"bytes,2,opt,name=MessageWarn,proto3" json:"MessageWarn,omitempty"`
	MessageError string `protobuf:"bytes,3,opt,name=MessageError,proto3" json:"MessageError,omitempty"`
}

func (x *OrchWebHookNewMasterResponse) Reset() {
	*x = OrchWebHookNewMasterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchestrator_webhook_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchWebHookNewMasterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchWebHookNewMasterResponse) ProtoMessage() {}

func (x *OrchWebHookNewMasterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_webhook_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchWebHookNewMasterResponse.ProtoReflect.Descriptor instead.
func (*OrchWebHookNewMasterResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_webhook_proto_rawDescGZIP(), []int{3}
}

func (x *OrchWebHookNewMasterResponse) GetMessageInfo() string {
	if x != nil {
		return x.MessageInfo
	}
	return ""
}

func (x *OrchWebHookNewMasterResponse) GetMessageWarn() string {
	if x != nil {
		return x.MessageWarn
	}
	return ""
}

func (x *OrchWebHookNewMasterResponse) GetMessageError() string {
	if x != nil {
		return x.MessageError
	}
	return ""
}

var File_orchestrator_webhook_proto protoreflect.FileDescriptor

var file_orchestrator_webhook_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x77,
	0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x61,
	0x61, 0x73, 0x64, 0x62, 0x22, 0x4c, 0x0a, 0x1c, 0x4f, 0x72, 0x63, 0x68, 0x57, 0x65, 0x62, 0x48,
	0x6f, 0x6f, 0x6b, 0x44, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x44, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x11, 0x44, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x87, 0x01, 0x0a, 0x1d, 0x4f, 0x72, 0x63, 0x68, 0x57, 0x65, 0x62, 0x48, 0x6f,
	0x6f, 0x6b, 0x44, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x57, 0x61, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x57, 0x61, 0x72, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x49, 0x0a, 0x1b,
	0x4f, 0x72, 0x63, 0x68, 0x57, 0x65, 0x62, 0x48, 0x6f, 0x6f, 0x6b, 0x4e, 0x65, 0x77, 0x4d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x4e,
	0x65, 0x77, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x4e, 0x65, 0x77, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x1c, 0x4f, 0x72, 0x63, 0x68,
	0x57, 0x65, 0x62, 0x48, 0x6f, 0x6f, 0x6b, 0x4e, 0x65, 0x77, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x61, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x61, 0x72, 0x6e, 0x12, 0x22, 0x0a, 0x0c,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x32, 0x77, 0x0a, 0x13, 0x4f, 0x70, 0x44, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x4f, 0x70,
	0x44, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x24, 0x2e, 0x73, 0x61, 0x61,
	0x73, 0x64, 0x62, 0x2e, 0x4f, 0x72, 0x63, 0x68, 0x57, 0x65, 0x62, 0x48, 0x6f, 0x6f, 0x6b, 0x44,
	0x65, 0x61, 0x64, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x73, 0x61, 0x61, 0x73, 0x64, 0x62, 0x2e, 0x4f, 0x72, 0x63, 0x68, 0x57, 0x65,
	0x62, 0x48, 0x6f, 0x6f, 0x6b, 0x44, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x73, 0x0a, 0x12, 0x4f, 0x70, 0x4e,
	0x65, 0x77, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x5d, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x4f, 0x70, 0x4e, 0x65, 0x77, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x23, 0x2e, 0x73, 0x61, 0x61, 0x73, 0x64, 0x62, 0x2e, 0x4f, 0x72, 0x63, 0x68, 0x57,
	0x65, 0x62, 0x48, 0x6f, 0x6f, 0x6b, 0x4e, 0x65, 0x77, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x61, 0x61, 0x73, 0x64, 0x62, 0x2e,
	0x4f, 0x72, 0x63, 0x68, 0x57, 0x65, 0x62, 0x48, 0x6f, 0x6f, 0x6b, 0x4e, 0x65, 0x77, 0x4d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x14,
	0x5a, 0x12, 0x2e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2f, 0x3b, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orchestrator_webhook_proto_rawDescOnce sync.Once
	file_orchestrator_webhook_proto_rawDescData = file_orchestrator_webhook_proto_rawDesc
)

func file_orchestrator_webhook_proto_rawDescGZIP() []byte {
	file_orchestrator_webhook_proto_rawDescOnce.Do(func() {
		file_orchestrator_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(file_orchestrator_webhook_proto_rawDescData)
	})
	return file_orchestrator_webhook_proto_rawDescData
}

var file_orchestrator_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_orchestrator_webhook_proto_goTypes = []interface{}{
	(*OrchWebHookDeadMasterRequest)(nil),  // 0: saasdb.OrchWebHookDeadMasterRequest
	(*OrchWebHookDeadMasterResponse)(nil), // 1: saasdb.OrchWebHookDeadMasterResponse
	(*OrchWebHookNewMasterRequest)(nil),   // 2: saasdb.OrchWebHookNewMasterRequest
	(*OrchWebHookNewMasterResponse)(nil),  // 3: saasdb.OrchWebHookNewMasterResponse
}
var file_orchestrator_webhook_proto_depIdxs = []int32{
	0, // 0: saasdb.OpDeadMasterService.NewOpDeadMaster:input_type -> saasdb.OrchWebHookDeadMasterRequest
	2, // 1: saasdb.OpNewMasterService.NewOpNewMaster:input_type -> saasdb.OrchWebHookNewMasterRequest
	1, // 2: saasdb.OpDeadMasterService.NewOpDeadMaster:output_type -> saasdb.OrchWebHookDeadMasterResponse
	3, // 3: saasdb.OpNewMasterService.NewOpNewMaster:output_type -> saasdb.OrchWebHookNewMasterResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orchestrator_webhook_proto_init() }
func file_orchestrator_webhook_proto_init() {
	if File_orchestrator_webhook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orchestrator_webhook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchWebHookDeadMasterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orchestrator_webhook_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchWebHookDeadMasterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orchestrator_webhook_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchWebHookNewMasterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orchestrator_webhook_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchWebHookNewMasterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orchestrator_webhook_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_orchestrator_webhook_proto_goTypes,
		DependencyIndexes: file_orchestrator_webhook_proto_depIdxs,
		MessageInfos:      file_orchestrator_webhook_proto_msgTypes,
	}.Build()
	File_orchestrator_webhook_proto = out.File
	file_orchestrator_webhook_proto_rawDesc = nil
	file_orchestrator_webhook_proto_goTypes = nil
	file_orchestrator_webhook_proto_depIdxs = nil
}
