// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: showprocesslist.proto

package grpc_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MySQLShowProcessListServiceClient is the client API for MySQLShowProcessListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MySQLShowProcessListServiceClient interface {
	NewShowProcesslist(ctx context.Context, in *ShowProcesslistRequest, opts ...grpc.CallOption) (*ShowProcesslistResponce, error)
}

type mySQLShowProcessListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMySQLShowProcessListServiceClient(cc grpc.ClientConnInterface) MySQLShowProcessListServiceClient {
	return &mySQLShowProcessListServiceClient{cc}
}

func (c *mySQLShowProcessListServiceClient) NewShowProcesslist(ctx context.Context, in *ShowProcesslistRequest, opts ...grpc.CallOption) (*ShowProcesslistResponce, error) {
	out := new(ShowProcesslistResponce)
	err := c.cc.Invoke(ctx, "/saasdb.MySQLShowProcessListService/NewShowProcesslist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MySQLShowProcessListServiceServer is the server API for MySQLShowProcessListService service.
// All implementations must embed UnimplementedMySQLShowProcessListServiceServer
// for forward compatibility
type MySQLShowProcessListServiceServer interface {
	NewShowProcesslist(context.Context, *ShowProcesslistRequest) (*ShowProcesslistResponce, error)
	mustEmbedUnimplementedMySQLShowProcessListServiceServer()
}

// UnimplementedMySQLShowProcessListServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMySQLShowProcessListServiceServer struct {
}

func (UnimplementedMySQLShowProcessListServiceServer) NewShowProcesslist(context.Context, *ShowProcesslistRequest) (*ShowProcesslistResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewShowProcesslist not implemented")
}
func (UnimplementedMySQLShowProcessListServiceServer) mustEmbedUnimplementedMySQLShowProcessListServiceServer() {
}

// UnsafeMySQLShowProcessListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MySQLShowProcessListServiceServer will
// result in compilation errors.
type UnsafeMySQLShowProcessListServiceServer interface {
	mustEmbedUnimplementedMySQLShowProcessListServiceServer()
}

func RegisterMySQLShowProcessListServiceServer(s grpc.ServiceRegistrar, srv MySQLShowProcessListServiceServer) {
	s.RegisterService(&MySQLShowProcessListService_ServiceDesc, srv)
}

func _MySQLShowProcessListService_NewShowProcesslist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowProcesslistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySQLShowProcessListServiceServer).NewShowProcesslist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saasdb.MySQLShowProcessListService/NewShowProcesslist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySQLShowProcessListServiceServer).NewShowProcesslist(ctx, req.(*ShowProcesslistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MySQLShowProcessListService_ServiceDesc is the grpc.ServiceDesc for MySQLShowProcessListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MySQLShowProcessListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saasdb.MySQLShowProcessListService",
	HandlerType: (*MySQLShowProcessListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewShowProcesslist",
			Handler:    _MySQLShowProcessListService_NewShowProcesslist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "showprocesslist.proto",
}
