// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: slow_log_query.proto

package grpc_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义获取慢日志需要的消息
type SlowLogQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MySQLIP   string                 `protobuf:"bytes,1,opt,name=MySQLIP,proto3" json:"MySQLIP,omitempty"`
	MySQLPort int32                  `protobuf:"varint,2,opt,name=MySQLPort,proto3" json:"MySQLPort,omitempty"`
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTIme   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=EndTIme,proto3" json:"EndTIme,omitempty"`
}

func (x *SlowLogQueryRequest) Reset() {
	*x = SlowLogQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_slow_log_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlowLogQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlowLogQueryRequest) ProtoMessage() {}

func (x *SlowLogQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slow_log_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlowLogQueryRequest.ProtoReflect.Descriptor instead.
func (*SlowLogQueryRequest) Descriptor() ([]byte, []int) {
	return file_slow_log_query_proto_rawDescGZIP(), []int{0}
}

func (x *SlowLogQueryRequest) GetMySQLIP() string {
	if x != nil {
		return x.MySQLIP
	}
	return ""
}

func (x *SlowLogQueryRequest) GetMySQLPort() int32 {
	if x != nil {
		return x.MySQLPort
	}
	return 0
}

func (x *SlowLogQueryRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SlowLogQueryRequest) GetEndTIme() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTIme
	}
	return nil
}

// 定义慢日志返回的消息
type SlowLogQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlowLogs string `protobuf:"bytes,1,opt,name=SlowLogs,proto3" json:"SlowLogs,omitempty"`
}

func (x *SlowLogQueryResponse) Reset() {
	*x = SlowLogQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_slow_log_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlowLogQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlowLogQueryResponse) ProtoMessage() {}

func (x *SlowLogQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slow_log_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlowLogQueryResponse.ProtoReflect.Descriptor instead.
func (*SlowLogQueryResponse) Descriptor() ([]byte, []int) {
	return file_slow_log_query_proto_rawDescGZIP(), []int{1}
}

func (x *SlowLogQueryResponse) GetSlowLogs() string {
	if x != nil {
		return x.SlowLogs
	}
	return ""
}

var File_slow_log_query_proto protoreflect.FileDescriptor

var file_slow_log_query_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x6c, 0x6f, 0x77, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x61, 0x61, 0x73, 0x64, 0x62, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xbd, 0x01, 0x0a, 0x13, 0x53, 0x6c, 0x6f, 0x77, 0x4c, 0x6f, 0x67, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x79, 0x53, 0x51, 0x4c,
	0x49, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x49,
	0x50, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x50, 0x6f, 0x72, 0x74, 0x12,
	0x38, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x45, 0x6e, 0x64,
	0x54, 0x49, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x49, 0x6d, 0x65, 0x22,
	0x32, 0x0a, 0x14, 0x53, 0x6c, 0x6f, 0x77, 0x4c, 0x6f, 0x67, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x6c, 0x6f, 0x77, 0x4c,
	0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x6c, 0x6f, 0x77, 0x4c,
	0x6f, 0x67, 0x73, 0x32, 0x68, 0x0a, 0x18, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x53, 0x6c, 0x6f, 0x77,
	0x4c, 0x6f, 0x67, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4c, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x47, 0x65, 0x74, 0x53, 0x6c, 0x6f, 0x77, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x12, 0x1b, 0x2e, 0x73, 0x61, 0x61, 0x73, 0x64, 0x62, 0x2e, 0x53, 0x6c, 0x6f, 0x77,
	0x4c, 0x6f, 0x67, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x73, 0x61, 0x61, 0x73, 0x64, 0x62, 0x2e, 0x53, 0x6c, 0x6f, 0x77, 0x4c, 0x6f, 0x67,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a,
	0x12, 0x2e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2f, 0x3b, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_slow_log_query_proto_rawDescOnce sync.Once
	file_slow_log_query_proto_rawDescData = file_slow_log_query_proto_rawDesc
)

func file_slow_log_query_proto_rawDescGZIP() []byte {
	file_slow_log_query_proto_rawDescOnce.Do(func() {
		file_slow_log_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_slow_log_query_proto_rawDescData)
	})
	return file_slow_log_query_proto_rawDescData
}

var file_slow_log_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_slow_log_query_proto_goTypes = []interface{}{
	(*SlowLogQueryRequest)(nil),   // 0: saasdb.SlowLogQueryRequest
	(*SlowLogQueryResponse)(nil),  // 1: saasdb.SlowLogQueryResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_slow_log_query_proto_depIdxs = []int32{
	2, // 0: saasdb.SlowLogQueryRequest.StartTime:type_name -> google.protobuf.Timestamp
	2, // 1: saasdb.SlowLogQueryRequest.EndTIme:type_name -> google.protobuf.Timestamp
	0, // 2: saasdb.MySQLSlowLogQueryService.NewGetSlowQuery:input_type -> saasdb.SlowLogQueryRequest
	1, // 3: saasdb.MySQLSlowLogQueryService.NewGetSlowQuery:output_type -> saasdb.SlowLogQueryResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_slow_log_query_proto_init() }
func file_slow_log_query_proto_init() {
	if File_slow_log_query_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_slow_log_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlowLogQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_slow_log_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlowLogQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_slow_log_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_slow_log_query_proto_goTypes,
		DependencyIndexes: file_slow_log_query_proto_depIdxs,
		MessageInfos:      file_slow_log_query_proto_msgTypes,
	}.Build()
	File_slow_log_query_proto = out.File
	file_slow_log_query_proto_rawDesc = nil
	file_slow_log_query_proto_goTypes = nil
	file_slow_log_query_proto_depIdxs = nil
}
