[MySQLManager]
mysqlmanager_user = "root"
mysqlmanager_password = "letsg0"

[GrpcServer]
creditsServeKey = "/Users/anderalex/go/src/workgrpc/certify/server.key"
creditsServeCrt = "/Users/anderalex/go/src/workgrpc/certify/server.crt"
protocol = "tcp"
listenPort = 3000

