[MySQLManager]
mysqlmanager_user = "root"
mysqlmanager_password = "letsg0"

[GrpcServer]
creditsServeKey = "/Users/haochen/go/src/saasdb/server/service/saasdb/cerify/server.key"
creditsServeCrt = "/Users/haochen/go/src/saasdb/server/service/saasdb/cerify/server.crt"
protocol = "tcp"
listenPort = 3000

