# 用于管理本地的MySQL
[MySQLManager]
mysqlmanager_user = "root"
mysqlmanager_password = "letsg0"

# 用于跟saasdb交互
[SaasDB]
SaasDBHost = "127.0.0.1"
SaasDBUser = "root"
SaasPassword = "letsg0"
SaasPort = 3307
SaasDBName = "saasdb"

# 用于GrpcServer的配置(saasdbAgent)
[GrpcServer]
creditsServeKey = "/Users/anderalex/go/src/saasdb/server/service/saasdb/cerify/server.key"
creditsServeCrt = "/Users/anderalex/go/src/saasdb/server/service/saasdb/cerify/server.crt"
protocol = "tcp"
listenPort = 3000


# 脚本目录
[Scripts]
scrpits_home_dir = ""
backup_mysql_scrpit_name = ""
