package saasdb

import "github.com/flipped-aurora/gin-vue-admin/server/service/saasdb/taskclient"

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	// 基础表结构 结构体注册服务
	InstanceService
	HostService
	DomainService
	ProjectService
	BackLogService
	// 数据库操作 结构体注册服务
	taskclient.TaskGroup
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
