package saasdb

import "github.com/flipped-aurora/gin-vue-admin/server/router/saasdb/taskclientroute"

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	InstanceRouter
	HostRouter
	DomainRouter
	ProjectRouter
	BackLogRouter
	taskclientroute.ShowProcessListRouter
	taskclientroute.HandleVariablesRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
